### ISSUE TITLE
OIDC not working (synapse) due to invalid JSON Web Key Set

### ISSUE THREAD

**Issue by HugoDelval** [jazzband/django-oauth-toolkit#986]
**Describe the bug**
I'm trying to make my django application as a open ID connect provider, and I'm doing this using django-oauth-toolkit. My issue is that the client I use (synapse : https://github.com/matrix-org/synapse/blob/develop/docs/openid.md) is giving me a JSON Web Key Set signature error during the authorization process

![image](https://user-images.githubusercontent.com/9109308/122063355-7a24a880-cdf0-11eb-863c-cb364074e91a.png)

I'm pretty sure my configuration on synapse's side is correct, I've tried to switch to another provider (github) and it worked. So the issue is on the django-oauth-toolkit side

**To Reproduce**
- install synapse
- configure synapse to use django+django-oauth-toolkit as an oidc (my config is bellow)
- try to authorize synapse

```yaml
oidc_providers:
  - idp_id: django_ex
    idp_name: "Example"
    idp_brand: "subdomain"
    issuer: "https://subdomain.example.com/o/"
    client_id: "REDACTED"
    client_secret: "REDACTED"
    scopes: ["openid"]
    user_mapping_provider:
      config:
         localpart_template: "test-token-1"
         display_name_template: "test token 1"
```

Configurations on django's side : 

**urls.py**
```python
urlpatterns = [
    path(
        "o/",
        include(
            (base_urlpatterns + oidc_urlpatterns, "oauth2_provider"), namespace="oauth2_provider"
        ),
    ),
    ...
]
```

**settings.py**

```python
OAUTH2_PROVIDER = {
    "OIDC_ENABLED": True,
    "SCOPES": {
        "openid": "OpenID Connect scope",
    },
}
```
\+ cors allowed using https://github.com/adamchainz/django-cors-headers

**Expected behavior**
The authorization flow should succeed

**Version**
django-oauth-toolkit==1.5.0

- [ ] I have tested with the latest published release and it's still a problem.
- [ ] I have tested with the master branch and it's still a problem.

**Additional context**
None

**Comment by HugoDelval** [comment]
Turns out I was missing a section in the synapse's configuration. The correct config would be : 

```yaml
oidc_providers:
  - idp_id: django_ex
    idp_name: "Example"
    idp_brand: "subdomain"
    issuer: "https://subdomain.example.com/o/"
    client_id: "REDACTED"
    client_secret: "REDACTED"
    scopes: ["openid"]
    user_profile_method: "userinfo_endpoint"
    user_mapping_provider:
      config:
         localpart_template: "test-token-1"
         display_name_template: "test token 1"
```

Sorry for the noise!
